<?php

namespace AppBundle\Repository;

/**
 * VehicleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getVehicles($vehicleIds){
//        var_dump($vehicleIds);exit;
        $query = $this->createQueryBuilder('v');
        $query->select('v');
        $query->where(
            $query->expr()->in('v.vehicleId',':vehicleIds')
        )->setParameter('vehicleIds',$vehicleIds);
        return $query->getQuery()->getResult();

    }
}
